---
general:
  healthcheckEvery: 60s
  httpClientTimeout: 5s
  refreshDashboardEvery: 5s
groups:
  - name: Community Services
    nodes:
      - name: Monappy
        endpoint: https://monappy.jp
        type: http_check
      - name: Mastodon for Monappy
        endpoint: https://mstdn.monappy.jp
        type: http_check
      - name: AskMona
        endpoint: http://askmona.org/
        type: http_check
      - name: PinkMona (Caution! R18)
        endpoint: http://pinkmona.org/
        type: http_check
  - name: Blockchain Explorers
    nodes:
      - name: Monaco-ex.org
        endpoint: https://mona.insight.monaco-ex.org/insight/
        type: http_check
      - name: Bhcain.info
        endpoint: https://bchain.info/MONA/
        type: http_check
      - name: Chainsight.info
        endpoint: https://mona.chainsight.info/
        type: http_check
      - name: Multi Light Block Explorer
        endpoint: http://namuyan.dip.jp/MultiLightBlockExplorer/index.php?page=selectcoin&coin=mona
        type: http_check
  - name: Exchanges
    nodes:
      - name: Zaif (MONA/BTC)
        endpoint: https://zaif.jp/trade_mona_btc
        type: http_check
      - name: Zaif (MONA/JPY)
        endpoint: https://zaif.jp/trade_mona_jpy
        type: http_check
      - name: Bitbank.cc
        endpoint: https://bitbank.cc/
        type: http_check
  - name: Online Wallets
    nodes:
      - name: monacoin.jp
        endpoint: https://monacoin.jp/
        type: http_check
  - name: Market Analysis
    nodes:
      - name: Monacoin Charts
        endpoint: http://mona-coin.com/
        type: http_check
  - name: Electrum servers
    nodes:
      - name: Tamami Foundation (ping)
        endpoint: electrumx.tamami-foundation.org
        type: ping_check
  - name: Official Site
    nodes:
      - name: Monacoin Project
        endpoint: https://monacoin.org/
        type: http_check
